use std::env;
use std::fs;
use std::path::PathBuf;

fn emit_embedded_public_runtime() {
    println!("cargo:rerun-if-env-changed=GPU_SHARK_EMBED_PUBLIC_RUNTIME");
    println!("cargo:rerun-if-env-changed=GPU_SHARK_PUBLIC_PAYLOAD_DIR");

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR must be set"));
    let generated = out_dir.join("embedded_public_runtime.rs");
    let enabled = env::var("GPU_SHARK_EMBED_PUBLIC_RUNTIME").as_deref() == Ok("1");
    let mut entries = Vec::new();
    if enabled {
        let payload_dir = PathBuf::from(
            env::var("GPU_SHARK_PUBLIC_PAYLOAD_DIR")
                .expect("GPU_SHARK_PUBLIC_PAYLOAD_DIR is required for a standalone build"),
        );
        let embedded_dir = out_dir.join("embedded-runtime");
        fs::create_dir_all(&embedded_dir).expect("create embedded runtime directory");
        for file_name in [
            "gs.dll",
            "gsn.dll",
            "libMonoPosixHelper.dll",
            "MonoPosixHelper.dll",
        ] {
            let source = payload_dir.join(file_name);
            if source.exists() {
                let destination = embedded_dir.join(file_name);
                fs::copy(&source, &destination).unwrap_or_else(|error| {
                    panic!("embed public runtime {}: {error}", source.display())
                });
                println!("cargo:rerun-if-changed={}", source.display());
                entries.push(format!(
                    "    (\"{file_name}\", include_bytes!(concat!(env!(\"OUT_DIR\"), \"/embedded-runtime/{file_name}\"))),"
                ));
            } else if matches!(file_name, "gs.dll" | "gsn.dll") {
                panic!(
                    "required public runtime file is missing: {}",
                    source.display()
                );
            }
        }
    }
    let source = format!(
        "// Generated by build.rs. Never add runtime payloads to source control.\npub static EMBEDDED_PUBLIC_RUNTIME: &[(&str, &[u8])] = &[\n{}\n];\n",
        entries.join("\n")
    );
    fs::write(generated, source).expect("write embedded runtime declaration");
}

fn emit_feedback_configuration() {
    println!("cargo:rerun-if-env-changed=GPU_SHARK_FEEDBACK_HOST");
    println!("cargo:rerun-if-env-changed=GPU_SHARK_FEEDBACK_PATH");

    let host = env::var("GPU_SHARK_FEEDBACK_HOST")
        .expect("GPU_SHARK_FEEDBACK_HOST is required to build the feedback client");
    let path = env::var("GPU_SHARK_FEEDBACK_PATH")
        .expect("GPU_SHARK_FEEDBACK_PATH is required to build the feedback client");
    assert!(!host.contains(['\r', '\n']), "invalid feedback host");
    assert!(
        path.starts_with('/') && !path.contains(['\r', '\n']),
        "invalid feedback path"
    );
    println!("cargo:rustc-env=GPU_SHARK_FEEDBACK_HOST={host}");
    println!("cargo:rustc-env=GPU_SHARK_FEEDBACK_PATH={path}");
}

fn main() {
    println!("cargo:rerun-if-changed=icon.ico");
    emit_embedded_public_runtime();
    emit_feedback_configuration();
    if cfg!(target_os = "windows") {
        let mut resource = winres::WindowsResource::new();
        let version = env!("CARGO_PKG_VERSION");
        resource.set_icon("icon.ico");
        resource.set("FileVersion", &format!("{version}.0"));
        resource.set("ProductVersion", version);
        resource.set("ProductName", "GPU Shark");
        resource.set("FileDescription", "GPU and CPU telemetry monitor");
        resource.set("LegalCopyright", "Copyright (c) 2026 k1gs");
        resource.set_manifest(
            r#"<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="requireAdministrator" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
    </windowsSettings>
  </application>
</assembly>"#,
        );
        resource.compile().expect("compile Windows resources");
    }
}
